// helloangular/src/app/todo/todo.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { Todos, Todo } from './todos';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css', '../common/common.css']
})
export class TodoComponent implements OnInit {

  private _todoList: Todos;

  constructor() { }

  ngOnInit(): void {
    this._todoList = new Todos();
    this._todoList.add('plz fix me!!');
  }

  toggleTodo(todo: Todo): void {
    this.log(() => 'called toggleTodo. todo=' + todo.text);
    this._todoList.toggle(todo);
  }

  addTodo(input: HTMLInputElement): void {
    this.log(() => 'called addTodo. todo=' + input.value);
    this._todoList.add(input.value)
    input.value = '';
  }

  @ViewChild('modifyinput')
  set modifyInput(_input: ElementRef | undefined) {
    this.log(() => 'called modifyInput. ElementRef=' + _input);
    if (_input !== undefined) {
      _input.nativeElement.focus();
    }
  }

  modifyTodo(todo: Todo, input: HTMLInputElement): void {
    this.log(() => 'called modifyTodo. beforetodo=' + todo.text + ', newtodo=' + input.value);
    this._todoList.modify(todo, input.value)
    input.value = '';
    this.switchMode(todo);
  }

  switchMode(todo: Todo): void {
    this.log(() => 'called switchMode. currentInputMode=' + todo.isInputMode() + ', nextInputMode=' + !todo.isInputMode());
    todo.switchMode();
  }

  isInputMode(todo: Todo): boolean {
    this.log(() => 'called isInputMode. currentInputMode=' + todo.isInputMode());
    return todo.isInputMode();
  }

  deleteTodo(todo: Todo): void {
    this.log(() => 'called deleteTodo. todo=' + todo.text);
    this._todoList.delete(todo);
  }

  deleteAllTodo(): void {
    this.log(() => 'called deleteAllTodo.');
    this._todoList.deleteAll();
  }

  // showDetail(todo: Todo): void {
  //   todo.detail.showDetail();
  // }

  // isShowDetail(todo: Todo): boolean {
  //   return todo.detail.isShowDetail();
  // }

  get todoList() {
    return this._todoList;
  }

  private log(message: () => string): void {
    console.log(message());
  }
}

<h2>TODO</h2>
<div>
    <ul>
        <li *ngFor="let todo of todoList.todos">
            <input type="checkbox" [checked]="todo.done" (change)="toggleTodo(todo)">
            <span *ngIf="!isInputMode(todo)" [ngClass]="{done: todo.done}"
                (dblclick)="switchMode(todo)">{{todo.text}}</span>
            <input *ngIf="isInputMode(todo)" type="text" [(ngModel)]="todo.text" #modifyinput
                (keyup.enter)="modifyTodo(todo, modifyinput)">
            <app-todo-detail [_todo]="todo"></app-todo-detail>
            <!-- span *ngIf="isShowDetail(todo)"> RegistDate:{{todo.detail.registDate | date:"yy/MM/dd HH:mm"}},
                UpdateDate:{{todo.detail.updateDate | date:"yy/MM/dd HH:mm"}}</span>
            <button [ngClass]="'button--green'" (click)="showDetail(todo)">detail</button -->
            <button [ngClass]="'button--green'" (click)="deleteTodo(todo)">del</button>
        </li>
        <li>
            <input type="text" #input (keyup.enter)="addTodo(input)">
        </li>
    </ul>
    <br />
    <button [ngClass]="'button--grey'" (click)="deleteAllTodo()">delAll</button>
</div>

// hellonuxt/pages/todo/index.vue
<template>
  <section class="container">
    <div>
      <ul>
        <li v-for="todo in todoList" :key="todo">
          <input type="checkbox" :checked="todo.done" @change="toggleTodo(todo)" />
          <span :class="{done: todo.done}">{{todo.text}}</span>
          <button class="button--green" @click="deleteTodo(todo)">del</button>
        </li>
        <li>
          <input placeholder="please write your todo!!" @keyup.enter="addTodo" />
        </li>
      </ul>
      <br />
      <button class="button--grey" @click="deleteAllTodo(todoList)">delAll</button>
    </div>
  </section>
</template>

<script>
import { mapMutations } from "vuex";

export default {
  layout: "generic",
  async fetch({ store, params }) {
    let todoList = store.state.todo.todoList;
    if (todoList.indexOf("plz fix me!!") == -1) {
      store.commit("todo/add", "plz fix me!!");
    }
  },
  computed: {
    todoList() {
      return this.$store.state.todo.todoList;
    }
  },
  methods: {
    addTodo(e) {
      this.$store.commit("todo/add", e.target.value);
      e.target.value = "";
    },
    ...mapMutations({
      toggleTodo: "todo/toggle",
      deleteTodo: "todo/delete",
      deleteAllTodo: "todo/deleteAll"
    })
  }
};
</script>

<style>
.done {
  text-decoration: line-through;
}
</style>
